### ISSUE TITLE
Promote one-year report

### ISSUE THREAD

**Issue by hannahkane** [mozilla/advocacy.mozilla.org#214] opened 2016-07-08 00:36 UTC
From @Melechuga in #165: We'd just want to link to it from both the adv.m.o page (one of the "tiles") and from the OWF page.

Do you want the link to replace one of the current four tiles on adv.m.o, or be a fifth tile?

Where do you think it would fit best on the OWF content (see "content only changes" versions on the [redpen](https://redpen.io/p/eb8f03d752fb5d93c5))?

**Comment by Melechuga** [comment] 2016-07-08 14:49
@hannahkane I think it would fit well at the end of the "About the Program" section on the OWF landing page. If there's a way to make it quite visible -- more than just a link -- that would be great; maybe a button that separates the "About" section from the "Expectations" section? I leave it to @kristinashu for design advice!

**Comment by kristinashu** [comment] 2016-07-08 22:24
Closing this ticket, it's a duplicate of https://github.com/mozilla/advocacy.mozilla.org/issues/202

**Closed by kristinashu** 2016-07-08 22:24 UTC
